services:
    service:
        container_name: project-template
        build:
            context: .
            dockerfile: ./Dockerfile
        volumes:
            - .:/code

        # overrides default command so things don't shut down after the process ends.
        command: /bin/sh -c "while sleep 1000; do :; done"
        # command: /bin/bash
