services:
    main:
        container_name: main
        build: .

        volumes:
            - type: bind
              source: .
              target: /workspace
        working_dir: /workspace

        # for mac arm chips see:
        # - https://docs.docker.com/desktop/troubleshoot/known-issues/
        # - https://github.com/IDEA-Research/Grounded-Segment-Anything/blob/main/Makefile
        
        # for nvidia gpus see:
        # - https://github.com/NVIDIA/nvidia-container-toolkit?tab=readme-ov-file
        # - https://docs.docker.com/compose/gpu-support/
        
        # config for pytorch IPC
        stdin_open: true
        tty: true
        ipc: host

        ports:
            - '8888:8888'
