services:
    main:
        container_name: project-template

        # use dockerfile to enable caching
        build: .

        # mount the current directory into the container
        user: root
        working_dir: /workspace
        volumes:
            - .:/workspace

        # pytorch multiprocessing support
        # for gpu access see: https://docs.docker.com/compose/gpu-support/
        stdin_open: true
        tty: true
        ipc: host

        # stay alive to exec into the container
        # command: tail -f /dev/null
