services:
    main:
        container_name: main
        # build: ./dockerfile
        dockerfile_inline: |
            # FROM --platform=linux/amd64 ubuntu:latest
            FROM ubuntu:20.04
            RUN apt-get update && apt-get install -y python3 python3-pip
            RUN pip install -r requirements.txt

            # jupyter server via http://localhost:8888/lab
            # RUN pip install jupyter jupyterlab jupyter_contrib_nbextensions
            # ENV JUPYTER_ENABLE_LAB=yes
            # EXPOSE 8888

        # command: ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser", "--ServerApp.token=''", "--ServerApp.password=''", "--ServerApp.allow_origin='*'", "--ServerApp.disable_check_xsrf=True", "--ServerApp.allow_root=True", "--ServerApp.open_browser=False"]
        command: ["tail", "-f", "/dev/null"]

        volumes:
            - type: bind
              source: .
              target: /workspace
        working_dir: /workspace
        ports:
            - '8888:8888'

        # for mac arm chips see:
        # - https://docs.docker.com/desktop/troubleshoot/known-issues/
        
        # for nvidia gpus see:
        # - https://github.com/IDEA-Research/Grounded-Segment-Anything/blob/main/Makefile
        # - https://github.com/NVIDIA/nvidia-container-toolkit?tab=readme-ov-file
        # - https://docs.docker.com/compose/gpu-support/
