# arm64: https://docs.docker.com/desktop/troubleshoot/known-issues/
# nvidia gpus: https://docs.docker.com/compose/gpu-support/

services:
  main:
    container_name: main
    volumes:
      - type: bind
        source: .
        target: /workspace
    working_dir: /workspace
    ports:
      - '8888:8888'
    build:
      context: .
      dockerfile_inline: |
        FROM --platform=linux/amd64 ubuntu:22.04

        ARG DEBIAN_FRONTEND=noninteractive
        RUN apt-get update
        RUN apt-get install -y ca-certificates
        RUN apt-get install -y python3 python3-pip
        
        WORKDIR /workspace
        COPY requirements.txt /workspace/requirements.txt
        RUN pip3 install --upgrade pip && pip3 install -r requirements.txt

        # RUN pip install jupyter jupyterlab jupyter_contrib_nbextensions
        # ENV JUPYTER_ENABLE_LAB=yes
        # EXPOSE 8888 # http://localhost:8888/lab
        # CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888", "--allow-root", "--no-browser", "--ServerApp.token=''", "--ServerApp.password=''", "--ServerApp.allow_origin='*'", "--ServerApp.disable_check_xsrf=True", "--ServerApp.allow_root=True", "--ServerApp.open_browser=False"]

        CMD ["tail", "-f", "/dev/null"]
